.gitignore
.travis.yml
AUTHORS
ChangeLog
requirements-dev.txt
setup.cfg
setup.py
tests/test_modules.py
tox.ini

* Adding Tox for faster multi-runtime testing
* Adding PBR for automatic versioning
* Auto publishing to pypi

Improve packaging

---

epsagon/events/botocore.py

Making sure data collection in botocore events are fail-safe.

collecting data in botocore events.

---

.gitignore
.travis.yml
epsagon/constants.py
scripts/publish.sh
setup.cfg
setup.py

PBR isn't working well, This will use python-semantic-release instead. The travis configuration should only run this on the master branch

revert pbr related changes and use python-semantic-release instread

---

epsagon/events/botocore.py

Handling with missing name on step function execution.

hotfix(botocore): handling with missing name on step function execution

---

epsagon/events/botocore.py

hotfix(events/botocore): handle DeleteRequest operation when wrapping dynamoDB

---

epsagon/events/botocore.py

Extract function name if found ARN format.

fix(botocore.py): extract function name arn format

---

epsagon/events/botocore.py
epsagon/trace.py

Adding support for firehose events.

feat(botocore): add firehose support

---

epsagon/events/urllib.py

fix(urllib): url detection in urllib

---

README.md
epsagon/events/dbapi.py
epsagon/trace.py
examples/custom_labels.py
tests/test_trace.py

+ fix(trace.py): support int/float labels

 fix(dbapi.py): extend query size

---

README.md

fix(README): update year

---

epsagon/events/botocore.py
epsagon/events/pynamodb.py
epsagon/modules/pynamodb.py

feat(pynamodb): add support for PynamoDB

---

epsagon/runners/aws_lambda.py

fix(aws_lambda.py): generate unique id for local run

---

epsagon/common.py
epsagon/constants.py
epsagon/runners/aws_lambda.py
epsagon/trace.py
epsagon/wrappers/aws_lambda.py
tests/test_trace.py
tests/wrappers/test_lambda_wrapper.py

Send traces in case of timeout

feat(timeout): send traces on timeouts

---

epsagon/modules/db_wrapper.py
epsagon/modules/psycopg2.py
requirements.txt

fix https://github.com/epsagon/epsagon-python/issues/50
Tested with all latest libs on 2.7 and 3.6 on Lambda

fix(requirements): open requirements for libs

---

epsagon/trace.py

this will calculate the duration again

terminate runner before sending traces

---

epsagon/events/botocore.py
epsagon/modules/botocore.py

In addition, adding support for vendored requests in botocore.

feat(botocore): add support for SSM

---

epsagon/trace.py
tests/test_trace.py

fix(trace.py): send requests in a single session

---

epsagon/trace.py
tests/test_trace.py

fix(trace.py): add token to the header

---

acceptance/acceptance.py
acceptance/lambda-handlers/serverless.yml
acceptance/run.sh
epsagon/trace.py

🆙 
also, applying the same trick to fix acceptance as it is in node.

fix(trace.py): support any object in trace encode

---

epsagon/runners/aws_lambda.py
tests/wrappers/test_lambda_wrapper.py

fix(aws_lambda.py): collect alias

---

epsagon/wrappers/django.py

fixing case where Content-Type does not exists

fix(django.py): fix ignore request in Django

---

acceptance/run.sh
epsagon/events/requests.py
epsagon/events/urllib3.py
epsagon/modules/requests.py
epsagon/modules/urllib3.py
epsagon/trace.py

Urllib3 support

---

epsagon/events/urllib3.py

fix(urllib3.py): remove `:` from url

---

epsagon/events/urllib3.py
epsagon/utils.py
tests/test_epsagon_init.py
tests/test_trace.py

fix(utils.py): set ignored urls via env

---

epsagon/events/requests.py
epsagon/utils.py
epsagon/wrappers/http_filters.py
package-lock.json
package.json

fix(http_filters.py): ignore aws urls only on requests

---

epsagon/events/requests.py
epsagon/events/urllib3.py
epsagon/trace.py
epsagon/wrappers/http_filters.py

Also ignoring AWS requests from urllib3

fix(trace.py): fix strip operation

---

epsagon/triggers/aws_lambda.py

fix(aws_lambda.py): extract api gateway domain name in trigger

---

epsagon/events/urllib3.py

fix(urllib3.py): modify unsupported format_map to format for all py versions

---

README.md

fix(README): re-publish package

---

epsagon/trace.py

fix(trace.py): extract traceback from exception

---

tests/test_trace.py

fixing some pylints to create a commit
I made a mistake and the latest changed wasn't released due to no semantic release, so i created this PR.

feat(trace.py): removing max events per type limitation

---

epsagon/triggers/aws_lambda.py

fix(aws_lambda): fix web trigger names to be domains

---

epsagon/modules/botocore.py

https://github.com/boto/botocore/pull/1829

fix(botocore.py): handle vendored requests removal

---

epsagon/events/urllib3.py
epsagon/modules/urllib3.py

Reverts epsagon/epsagon-python#157

Revert "feat(urllib3): add header to support opentracing connections"

---

epsagon/modules/urllib3.py

fix(urllib3): fixing case of empty headers

---

epsagon/events/botocore.py
epsagon/triggers/aws_lambda.py
requirements-dev.txt
requirements.txt
setup.py

having boto3 in our requirements add unnecessary size to our package, and can create inconsistencies in Lambda functions

fix(botocore): remove boto3 requirement

---

epsagon/event.py
epsagon/utils.py
epsagon/wrappers/django.py
epsagon/wrappers/flask.py

1. Catching errors in django library.
2. Set error in event only if there is no excpetions.
3. Getting tracebak from excpetion moved to common from flask.

feat(django): catching django excpetions

---

epsagon/runners/flask.py
epsagon/utils.py

In addition adding some fields to flask

fix(utils.py): unset ECS data if no labels found

---

README.md
epsagon/modules/logging.py
epsagon/utils.py
tests/test_epsagon_init.py
tests/test_trace.py

* Handling JSON messages
* Set it on by default for logging calls
* Disable on Lambda envs (added test)

fix(logging): update logging instrumentation behaviour

---

epsagon/modules/logging.py

Instrumenting the calls, even without changing anything, can cause behavior change (the module name is changed).
Hence, moving the `if trace_factory.is_logging_tracing_enabled():` to the instrumentation level

fix(logging.py): enable logging tracing at the inst level

---

epsagon/modules/logging.py

default was set to false although it is incorrect

fix(logging.py): fix default logging exception capture behavior

---

epsagon/modules/logging.py

Reverts epsagon/epsagon-python#242

Revert "fix(logging.py): fix default logging exception capture behavior"

---

epsagon/wrappers/chalice.py
package-lock.json

fixes https://github.com/epsagon/epsagon-python/issues/253

fix(chalice.py): fix local chalice runs

---

epsagon/trace.py
tests/conftest.py
tests/modules/test_logging.py
tests/test_trace.py
tests/wrappers/test_flask_wrapper.py
tests/wrappers/test_python_function.py

Working on transport fixture to UT

---

epsagon/wrappers/django.py

fixes https://github.com/epsagon/epsagon-python/issues/275

fix(django.py): fix missing django exceptions

---

epsagon/events/requests.py
epsagon/events/urllib3.py

Reverts epsagon/epsagon-python#286

fix(requests, urllib3): Reverting last fix due to bug

---

README.md

Fixed in previous PR, forcing release

fix(tracer): unicode encoding

---

epsagon/events/redis.py
epsagon/events/urllib3.py
epsagon/modules/logging.py
epsagon/modules/redis.py
epsagon/modules/tornado.py
epsagon/runners/tornado.py
epsagon/utils.py

Reverts epsagon/epsagon-python#314

fix(tornado.py): revert fix tornado mis-handle of 404s

---

package-lock.json
package.json

Reverts epsagon/epsagon-python#295

fix(deps): revert bump semantic-release from 15.13.30 to 17.2.3

---

epsagon/__init__.py
epsagon/events/qcloud_cos.py
epsagon/http_filters.py
epsagon/modules/qcloud_cos.py
epsagon/runners/tencent_function.py
epsagon/triggers/tencent_function.py
epsagon/wrappers/__init__.py
epsagon/wrappers/tencent_function.py

Tested all trigger types, and outbound calls to COS. 1 example:

feat(tencent): support tencent functions

---

epsagon/triggers/aws_lambda.py

Feat (Cognito) support Lambda Trigger

---

epsagon/events/urllib3.py

Reverts epsagon/epsagon-python#351

fix(urllib3): Revert "fix/urrlib3-event-collection-failed"

---

requirements-dev.txt

Makes building on macOS a little easier

fix(deps): switch to psycopg2-binary

---

README.md
epsagon/wrappers/aws_lambda.py
tests/wrappers/test_lambda_wrapper.py

feat(aws_lambda): do not trace warmup events from serverless-plugin-warmup plugin

---

epsagon/events/botocore.py

feat: add support ses v2

---

README.md
epsagon/constants.py
epsagon/event.py

https://epsagon.atlassian.net/browse/CS-191

fix(event): adding env var to allow cutting exception data
