AUTHORS, ChangeLog, scripts/publish.sh
I think that travis might be using old versions of one of the release packages that doesn't send `long_description_content_type` so this updates those packages.
also removing authors and changelog files that are not maintained automatically anymore.
=> Fix long description content type

requirements.txt
due to security risk in the previous version.
=> hotfix(requirements): update requests module

epsagon/common.py, epsagon/trace.py, epsagon/utils.py, tests/test_trace.py
This PR includes:
1. Adding debug flag to epsagon init so it will be easier to turn on / off debug mode
2. Printing errors that occur during the transmission of traces
=> Add debug flag and capture transmission errors

epsagon/wrappers/return_value.py
=> fix(return_value): limit return value size

README.md, epsagon/__init__.py, epsagon/trace.py, tests/test_trace.py
```python
epsagon.error(ValueError('Wrong something'), ''.join(traceback.extract_stack().format()) )
```
=> feat(trace.py): adding set_error to set runner exception

epsagon/wrappers/http_filters.py
Since releasing https://github.com/epsagon/epsagon-python/pull/70, we capture all botocore requests twice (once regular, and once as an HTTP req). this PR fixes it.
=> fix(http_filters): filter amazonaws requests

README.md
This release was skipped https://github.com/epsagon/epsagon-python/pull/87
=> feat(urllib3.py): release skipped urllib3 feature

epsagon/events/urllib3.py, epsagon/modules/urllib3.py
There was a duplication in wrapping.
In addition, response.data was reading the fp data, so it left the user without data.
=> fix(urllib3.py): fix duplication and data extraction error

epsagon/wrappers/flask.py
Fixing cases for endpoint like `/something/<id>`.
request.path = `/something/1`, where request.url_rule.rule = `/something/<id>`.
=> fix(flask.py): ignore flask url_rule and not path

README.md, epsagon/__init__.py, epsagon/wrappers/__init__.py, epsagon/wrappers/chalice.py
this needed since when we wrap the app, the user can't access to `app.attrs` (any attr).
=> fix(chalice.py): add Chalice specific wrapper

epsagon/modules/tornado.py, epsagon/runners/tornado.py, epsagon/wrappers/django.py, epsagon/wrappers/flask.py
Fixing host as resource name for Tornado, and set runner for all web frameworks
=> fix(flask.py): fix web frameworks tracer and host

epsagon/modules/tornado.py, epsagon/wrappers/django.py, epsagon/wrappers/flask.py, tests/wrappers/test_flask_wrapper.py
=> fix(flask.py): fix web frameworks sending two runners

epsagon/constants.py, epsagon/modules/tornado.py, epsagon/runners/tornado.py
using `finish` instead of `on_finish`.
Also reporting errors only on >=500.
And setting the local version to be 0.0.0-dev (used only in local tests).
=> fix(tornado.py): change finish wrapper

epsagon/constants.py, epsagon/events/httplib2.py, epsagon/events/requests.py, epsagon/events/urllib.py, epsagon/events/urllib3.py, epsagon/modules/tornado.py, epsagon/trace.py, epsagon/utils.py, epsagon/wrappers/flask.py, epsagon/wrappers/http_filters.py, epsagon/wrappers/python_function.py, tests/wrappers/test_flask_wrapper.py, tests/wrappers/test_lambda_wrapper.py, tests/wrappers/test_python_function.py
In addition:
1. Changed multiple tracers in Flask. This caused some other unrelated tests to break, since tracer_factory is global. Fixed.
2. Collect ECS task metadata in tornado.
3. Fixed task metadata event removal. which caused runner removal.
=> fix(http): allow custom error code

epsagon/events/botocore.py, epsagon/trace.py
conditions will be formatted using the built-in boto3 lib, like:
```
BuiltConditionExpression(condition_expression='(#n0 = :v0 AND #n1 = :v1)', attribute_name_placeholders={'#n0': 'main', '#n1': 'uniqueId'}, attribute_value_placeholders={':v0': 'order', ':v1': 1})
```
=> fix(botocore.py): fix DynamoDB conditions formatting

epsagon/triggers/aws_lambda.py
Add support for the following API Gateway mapping template:
```{
"operation": "GetViews",
"httpMethod": "$context.httpMethod",
"environment": "$stageVariables.environment",
"body" : $input.json("$"),
"identity": {
#foreach($key in $context.identity.keySet())
"$key": "$context.identity.get($key)"
#if($foreach.hasNext), #end
#end
},
"headers": {
#foreach($param in $input.params().header.keySet())
"$param": "$util.escapeJavaScript($input.params().header.get($param))"
#if($foreach.hasNext),
#end
#end
},
"queryParams": {
#foreach($param in $input.params().querystring.keySet())
"$param": "$util.escapeJavaScript($input.params().querystring.get($param))"
#if($foreach.hasNext),
#end
#end
},
"pathParams": {
#foreach($param in $input.params().path.keySet())
"$param": …
```
=> fix(triggers): support api gateway mapping templates

epsagon/events/botocore.py, epsagon/events/pynamodb.py, epsagon/events/urllib3.py, epsagon/modules/pynamodb.py, epsagon/modules/requests.py
The new version of pynamodb is no longer using `botocore.vendored.requests`.
In addition, putting back instrumentation for requests library, since it captures also the payload (which we can't in urllib3).
=> fix(pynamodb.py): update support for pynamodb 4

README.md, epsagon/wrappers/django.py
Use ignored_endpoints to blacklist specific paths and prevent Epsagon from sending a trace.
=> feat(django): prevent epsagon from sending tracing to paths in django

epsagon/events/botocore.py, epsagon/modules/botocore.py, epsagon/triggers/aws_lambda.py, epsagon/utils.py
Add support to the following functions: send_task_success, send_task_heartbeat, describe_execution
Add support to step function lambda triggered by SQS
=> feat(stepfunctions): Improve aws stepfunctions support

README.md, epsagon/trace.py, epsagon/utils.py, tests/test_epsagon_init.py, tests/test_trace.py
Filtering resource metadata by allows keys, Only branches that contain keys from keys_to_allow will be sent to epsagon.
=> feat(allow-whitelist-keys): allow whitelist keys in metadata

epsagon/common.py, epsagon/event.py, epsagon/events/azure.py, epsagon/events/botocore.py, epsagon/modules/logging.py, epsagon/trace.py, tests/modules/test_logging.py, tests/test_trace.py
Currently `EpsagonException` is being used from exceptions that we capture from logs (logging.exception). The name is confusing since it implies that Epsagon had an error. To make it as simple as possible, we'll use the base exception, and add another param `from_logs`
currently:
=> fix(trace.py): remove EpsagonException

epsagon/http_filters.py, epsagon/runners/python_function.py, epsagon/trace.py, epsagon/wrappers/flask.py, tests/events/test_eventbridge.py, tests/wrappers/common.py, tests/wrappers/test_fastapi_wrapper.py, tests/wrappers/test_flask_wrapper.py, tests/wrappers/test_lambda_wrapper.py
- no traces will be created if there is no runner. (splitting get_trace and get_or_create_trace)
- catching failure at send traces , avoiding "zombie" traces
- async mode: cleaning tracer from task after its being sent
=> Fix memory leaks ep 5511

epsagon/events/redis.py, epsagon/events/urllib3.py, epsagon/modules/logging.py, epsagon/modules/redis.py, epsagon/modules/tornado.py, epsagon/runners/tornado.py, epsagon/utils.py
In addition:
1. capturing redis response
2. support older redis versions
3. fixing edge case in urllib3
4. fixing log-correlation that was always handled as False (since trace_factory was not initialized)
5. adding some debug prints to Tornado
=> fix(tornado.py): fix tornado mis-handle of 404s

epsagon/modules/kafka.py, tests/events/test_kafka.py
Solves `AssertionError: Headers not supported in v0/v1` error that happens when we add header on older API versions of Kafka
=> fix(kafka.py): avoid setting headers in Kafka V0/V1

epsagon/events/celery.py, epsagon/runners/celery.py
since some version, `prepare` does not create a trace anymore, causing celery to stop working. So we're changing it to `get_or_create_trace`
fixes: https://github.com/epsagon/epsagon-python/issues/345
=> fix(celery.py): fix celery trace creation

epsagon/utils.py, requirements-dev.txt
Instead of getting this:
`Unable to import module 'epsagon': Failed to import module: index`
Get this:
`Unable to import module 'epsagon': Failed to import module: lambda_function, Error: No module named 'mod'`
(this will expose the real import error to the user)
=> fix(utils.py): show original import error

.travis.yml, scripts/run_acceptance_tests.sh
Currently it is not possible to run travis builds on PRs originated from forks. This is due to the fact that travis doesn't use the configured build secrets for unauthorized users (as it might be a security risk).
In order to overcome it, acceptance tests will run as they always have for authorized users. For unauthorized users, acceptance tests will run only after merge to master. Issues with acceptance tests will have to be addressed before a new version is published.
=> fix(travis): allow PRs from forks

epsagon/trace_transports.py, scripts/run_acceptance_tests.sh, scripts/run_tests.sh, tests/test_trace.py, tests/test_transports.py
When HTTPTransport was getting a timeout while trying to send out traces, it was retrying to send those traces (because of urlib3 configuration), this resulted in application delays when the url is unreachable.
Now the urlib3 in HTTPTransport is configured to not have any retries on failed attempts to reach the url.
=> fix(HTTPTransport): No retries will be made when trying to reach url and getting a timeout

epsagon/events/pymongo.py, epsagon/modules/pymongo.py
https://epsagon.atlassian.net/browse/CS-119
=> fix(pymongo): extend support for more operations
